image: archlinux
packages:
  - base-devel
  - docker
  - git
  - go
sources:
  - https://git.sr.ht/~poldi1405/gomod-recter
secrets:
  - bcefbc88-3c6d-48d1-8505-7a0df2e56062
  - a4a77b05-94e0-443c-9408-b2d81f7263fe
  - b15309e0-8156-44c8-aa7c-58c0f0b7d503
tasks:
  - prepare: |
      sudo usermod -aG docker build
      sudo systemctl start docker
  - mirror-to-github: |
      git clone --mirror https://git.sr.ht/~poldi1405/gomod-recter
      cd gomod-recter.git
      git push --mirror git@github.com:mpldr/gomod-recter.git
  - run-tests: |
      cd ~/gomod-recter
      make run-goss-test
  - build-container: |
      cd ~/gomod-recter
      git describe --exact-match HEAD || echo commit not tagged. No docker build. ; complete-build      
      make docker || make docker && make push
